[package]
name = "jrlib-logging"
version = "0.1.0"
edition = "2021"

[dependencies]
jrinx-abi = { path = "../../../abi", features = ["sysfn"] }
log = { version = "0.4.21", default-features = false }
spin = "0.9.8"
