[toolchain]
channel = "nightly-2024-03-08"
components = ["rust-src", "rustfmt", "clippy", "llvm-tools"]
profile = "minimal"
targets = [
    "riscv32imac-unknown-none-elf",
    "riscv64gc-unknown-none-elf",
]
