[package]
name = "jrinx-stack-alloc"
version = "0.1.0"
edition = "2021"

[dependencies]
jrinx-addr = { path = "../addr" }
jrinx-config = { path = "../config" }
jrinx-error = { path = "../error" }
spin = "0.9.8"
