[package]
name = "jrinx-devprober"
version = "0.1.0"
edition = "2021"

[dependencies]
fdt = { version = "0.1.5", default-features = false }
jrinx-devprober-macro = { path = "../devprober-macro" }
jrinx-error = { path = "../error" }
jrinx-layout = { path = "../layout" }
