[package]
name = "jrlib-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
a653rs = { version = "0.4.1", default-features = false, features = ["bindings"] }
jrinx-abi = { version = "0.1.0", path = "../../../abi" }
