[package]
name = "jrinx-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
elf = { version = "0.7.4", default-features = false }
jrinx-addr = { path = "../addr" }
jrinx-config = { path = "../config" }
jrinx-error = { path = "../error" }
