[package]
name = "jrlib-a653"
version = "0.1.0"
edition = "2021"

[dependencies]
jrinx-abi = { version = "0.1.0", path = "../../../abi", features = ["sysfn"]}
jrinx-apex = { version = "0.1.0", path = "../../../apex" }
